-- Tabel demo CRUD "aset" (skill halaman-cube, Resep A via driver Supabase).
-- Jalankan di Postgres/Supabase target (mis. gajah) untuk mereproduksi uji E2E.
-- Anon key mengakses lewat RLS; policy permissive HANYA tabel demo ini.
-- Uji perdana 20 Jul: dibuat di gajah, CRUD terbukti (insert/select/update/delete/
-- count), lalu DIDROP (cleanup). Rekreasi dgn file ini bila ingin menjalankan lagi.

create table if not exists public.phpvb_demo_aset (
  id          bigint generated by default as identity primary key,
  nama        text not null,
  spesifikasi text,
  kategori    text,          -- tetap | lancar | tb | keuangan | sdm
  jumlah      integer default 0,
  created_at  timestamptz default now()
);

alter table public.phpvb_demo_aset enable row level security;

drop policy if exists demo_aset_all on public.phpvb_demo_aset;
create policy demo_aset_all on public.phpvb_demo_aset
  for all to anon using (true) with check (true);

grant select, insert, update, delete on public.phpvb_demo_aset to anon;

-- PostgREST melihat tabel baru (schema cache reload):
notify pgrst, 'reload schema';

-- MySQL/MeekroDB (driver default) — padanan skema (ganti identity → AUTO_INCREMENT):
--   CREATE TABLE phpvb_demo_aset (
--     id INT AUTO_INCREMENT PRIMARY KEY, nama VARCHAR(255) NOT NULL,
--     spesifikasi TEXT, kategori VARCHAR(32), jumlah INT DEFAULT 0,
--     created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
